#services:
#  mssql:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    container_name: Sidecar
#    ports:
#      - "1432:1433"
#    environment:
#      ACCEPT_EULA: "Y"
#      SA_PASSWORD: "StrongPassword@123"
#    restart: unless-stopped