-- MERGE INTO blacklisted_merchants AS target
-- USING (VALUES
--     ('9047', 'Slay Devil Ent', 3),
--     ('1034', 'SITTA Ent', 3),
--     ('15', 'Rayder rad', 3),
--     ('20000987', 'Layla''s Place', 3)
-- ) AS src(merchant_id, merchant_name, suspicion_count)
-- ON target.merchant_id = src.merchant_id
-- WHEN NOT MATCHED THEN
--     INSERT (merchant_id, merchant_name, suspicion_count, black_listed_at)
--     VALUES (src.merchant_id, src.merchant_name, src.suspicion_count, GETDATE());
